#!/usr/bin/env bash

# Update the system
sudo apt update
sudo apt upgrade -y

# Install Nginx
sudo apt install nginx -y

# Configure Nginx to listen on port 80
sudo sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart

# Create an index.html file with "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index.html

# Make sure the ownership and permissions are set correctly
sudo chown -R www-data:www-data /var/www/html
sudo chmod -R 755 /var/www/html#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
# print "Hello World"

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
